name: AWS OIDC Demo

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::520578320765:role/Trust-Relationships
          aws-region: us-east-1
      - name: Verify Identity
        run: aws sts get-caller-identity

      - name: List S3 Buckets 
        run: aws s3 ls
      - name: List EC2 Instances 
        run: aws ec2 describe-instances
       
